# Generated by Django 5.0.6 on 2026-08-30 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер столика')),
                ('seats', models.PositiveIntegerField(default=2, verbose_name='К-сть місць')),
                ('pos_x', models.FloatField(default=50, verbose_name='Позиція X (%)')),
                ('pos_y', models.FloatField(default=50, verbose_name='Позиція Y (%)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний (доступний для бронювання)')),
            ],
            options={
                'verbose_name': 'Столик',
                'verbose_name_plural': 'Столики',
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name="Ім'я та прізвище")),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('guests', models.PositiveIntegerField(default=2, verbose_name='К-сть гостей')),
                ('date', models.DateField(verbose_name='Дата')),
                ('time_slot', models.CharField(choices=[('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], max_length=5, verbose_name='Час')),
                ('status', models.CharField(choices=[('confirmed', 'Підтверджено'), ('cancelled', 'Скасовано')], default='confirmed', max_length=20)),
                ('comment', models.TextField(blank=True, verbose_name='Коментар')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.table')),
            ],
            options={
                'verbose_name': 'Бронювання',
                'verbose_name_plural': 'Бронювання',
                'ordering': ['-date', 'time_slot'],
            },
        ),
    ]
