# Generated by Django 5.1.15 on 2026-09-20 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ready_notified',
            field=models.BooleanField(default=True, verbose_name='Клієнта повідомлено про готовність'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Прийнято'), ('confirmed', 'Готується'), ('ready', 'Готове до видачі'), ('done', 'Видано')], default='new', max_length=15, verbose_name='Статус'),
        ),
    ]
